### PR TITLE
Issue 18

### LINKED ISSUE #18: Add more resources for Git and GitHub section
Can I add few more resources to the **Git and Github** section like
- documentation version
- Learn git branching?

### PR DESCRIPTION
**Pull request by Greeshma2903**
Added 4 resources under the **Git and GitHub** section

### CODE REVIEW

**Comment by Greeshma2903** [comment]
I noticed a typo in the README GitHub part, can I correct that as well?
image

**Comment by arpit456jain** [comment]
Sure @Greeshma2903

**Comment by arpit456jain** [comment]
Thanks @Greeshma2903 for your valuable contribution

**Comment by Greeshma2903** [comment]
> Thanks @Greeshma2903 for your valuable contribution

🙌🙌

**Pull request merged**
